# Generated by Django 3.2.6 on 2021-09-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barbecue',
        ),
        migrations.DeleteModel(
            name='Fireplace',
        ),
        migrations.DeleteModel(
            name='Stove',
        ),
    ]
